### ISSUE TITLE
nodejs Version

### ISSUE THREAD

**Issue by clebert** [kof/node-linter#1]
Bitte die nodejs Version in der package.json hochsetzen.
Bei veralteter Version kommt beim starten der Fehler:

Error: Cannot find module 'vm'
    at resolveModuleFilename (node.js:265:13)
    at loadModule (node.js:231:20)
    at require (node.js:291:14)
    at Object.<anonymous> (/usr/local/lib/node/.npm/linter/0.0.2/package/lib/linter.js:2:10)
    at Module._compile (node.js:348:23)
    at Object..js (node.js:356:12)
    at Module.load (node.js:279:25)
    at loadModule (node.js:251:12)
    at require (node.js:291:14)
    at Object.<anonymous> (/usr/local/lib/node/.npm/linter/0.0.2/package/index.js:1:80)

**Comment by kof** [comment]
Closed by 6e6d1a226318968f826c0c4a167f3ffcb26a3e6e, #2. move formatting option to the lib from cli
