### ISSUE TITLE
issue installing by normal mean

### ISSUE THREAD

**Issue by c4milo** [kof/node-linter#6]
npm install linter
argsparser@0.0.5 ./node_modules/linter/node_modules/argsparser
uglify-js@1.0.2 ./node_modules/linter/node_modules/sharedjs/node_modules/uglify-js
sharedjs@0.0.2 ./node_modules/linter/node_modules/sharedjs

> linter@0.0.7 install /Users/camilo/Dropbox/Development/foo/bar/node_modules/linter
> make install

cd ./deps/closure-linter && python ./setup.py install 
running install
install_dir /opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

```
[Errno 13] Permission denied: '/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/test-easy-install-6518.write-test'
```

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

```
/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/
```

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  http://packages.python.org/distribute/easy_install.html

Please make the appropriate changes for your system and try again.

make: **\* [install] Error 1
npm ERR! error installing linter@0.0.7 Error: linter@0.0.7 install: `make install`
npm ERR! error installing linter@0.0.7 `sh "-c" "make install"` failed with 2
npm ERR! error installing linter@0.0.7     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing linter@0.0.7     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing linter@0.0.7     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! linter@0.0.7 install: `make install`
npm ERR! `sh "-c" "make install"` failed with 2
npm ERR! 
npm ERR! Failed at the linter@0.0.7 install script.
npm ERR! This is most likely a problem with the linter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make install
npm ERR! You can get their info via:
npm ERR!     npm owner ls linter
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 10.7.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "linter"
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/camilo/Dropbox/Development/foo/bar/npm-debug.log
npm not ok

**Comment by kof** [comment]
thanks for report, will investigate.

**Comment by c4milo** [comment]
a more useful output 

camilo@localhost:~/Dropbox/Development/foo/bar> npm install linter 
argsparser@0.0.5 ./node_modules/linter/node_modules/argsparser
argsparser@0.0.5 ./node_modules/linter/node_modules/sharedjs/node_modules/argsparser
uglify-js@1.0.2 ./node_modules/linter/node_modules/sharedjs/node_modules/uglify-js
sharedjs@0.0.2 ./node_modules/linter/node_modules/sharedjs

> linter@0.0.7 install /Users/camilo/Dropbox/Development/foo/bar/node_modules/linter
> make install

cd ./deps/closure-linter && python ./setup.py install 
running install
running bdist_egg
running egg_info
creating closure_linter.egg-info
writing requirements to closure_linter.egg-info/requires.txt
writing closure_linter.egg-info/PKG-INFO
writing top-level names to closure_linter.egg-info/top_level.txt
writing dependency_links to closure_linter.egg-info/dependency_links.txt
writing entry points to closure_linter.egg-info/entry_points.txt
writing manifest file 'closure_linter.egg-info/SOURCES.txt'
reading manifest file 'closure_linter.egg-info/SOURCES.txt'
writing manifest file 'closure_linter.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.6-universal/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/closure_linter
copying closure_linter/**init**.py -> build/lib/closure_linter
copying closure_linter/checker.py -> build/lib/closure_linter
copying closure_linter/checkerbase.py -> build/lib/closure_linter
copying closure_linter/ecmalintrules.py -> build/lib/closure_linter
copying closure_linter/ecmametadatapass.py -> build/lib/closure_linter
copying closure_linter/error_fixer.py -> build/lib/closure_linter
copying closure_linter/errorrules.py -> build/lib/closure_linter
copying closure_linter/errors.py -> build/lib/closure_linter
copying closure_linter/fixjsstyle.py -> build/lib/closure_linter
copying closure_linter/fixjsstyle_test.py -> build/lib/closure_linter
copying closure_linter/full_test.py -> build/lib/closure_linter
copying closure_linter/gjslint.py -> build/lib/closure_linter
copying closure_linter/indentation.py -> build/lib/closure_linter
copying closure_linter/javascriptlintrules.py -> build/lib/closure_linter
copying closure_linter/javascriptstatetracker.py -> build/lib/closure_linter
copying closure_linter/javascriptstatetracker_test.py -> build/lib/closure_linter
copying closure_linter/javascripttokenizer.py -> build/lib/closure_linter
copying closure_linter/javascripttokens.py -> build/lib/closure_linter
copying closure_linter/statetracker.py -> build/lib/closure_linter
copying closure_linter/tokenutil.py -> build/lib/closure_linter
creating build/lib/closure_linter/common
copying closure_linter/common/**init**.py -> build/lib/closure_linter/common
copying closure_linter/common/error.py -> build/lib/closure_linter/common
copying closure_linter/common/erroraccumulator.py -> build/lib/closure_linter/common
copying closure_linter/common/errorhandler.py -> build/lib/closure_linter/common
copying closure_linter/common/errorprinter.py -> build/lib/closure_linter/common
copying closure_linter/common/filetestcase.py -> build/lib/closure_linter/common
copying closure_linter/common/htmlutil.py -> build/lib/closure_linter/common
copying closure_linter/common/lintrunner.py -> build/lib/closure_linter/common
copying closure_linter/common/matcher.py -> build/lib/closure_linter/common
copying closure_linter/common/position.py -> build/lib/closure_linter/common
copying closure_linter/common/simplefileflags.py -> build/lib/closure_linter/common
copying closure_linter/common/tokenizer.py -> build/lib/closure_linter/common
copying closure_linter/common/tokens.py -> build/lib/closure_linter/common
creating build/bdist.macosx-10.6-universal
creating build/bdist.macosx-10.6-universal/egg
creating build/bdist.macosx-10.6-universal/egg/closure_linter
copying build/lib/closure_linter/**init**.py -> build/bdist.macosx-10.6-universal/egg/closure_linter
copying build/lib/closure_linter/checker.py -> build/bdist.macosx-10.6-universal/egg/closure_linter
copying build/lib/closure_linter/checkerbase.py -> build/bdist.macosx-10.6-universal/egg/closure_linter
creating build/bdist.macosx-10.6-universal/egg/closure_linter/common
copying build/lib/closure_linter/common/**init**.py -> build/bdist.macosx-10.6-universal/egg/closure_linter/common
copying build/lib/closure_linter/common/error.py -> build/bdist.macosx-10.6-universal/egg/closure_linter/common
copying build/lib/closure_linter/common/erroraccumulator.py -> build/bdist.macosx-10.6-universal/egg/closure_linter/common
copying build/lib/closure_linter/common/errorhandler.py -> build/bdist.macosx-10.6-universal/egg/closure_linter/common
copying build/lib/closure_linter/common/errorprinter.py -> build/bdist.macosx-10.6-universal/egg/closure_linter/common
copying build/lib/closure_linter/common/filetestcase.py -> build/bdist.macosx-10.6-universal/egg/closure_linter/common
copying build/lib/closure_linter/common/htmlutil.py -> build/bdist.macosx-10.6-universal/egg/closure_linter/common
copying build/lib/closure_linter/common/lintrunner.py -> build/bdist.macosx-10.6-universal/egg/closure_linter/common
copying build/lib/closure_linter/common/matcher.py -> build/bdist.macosx-10.6-universal/egg/closure_linter/common
copying build/lib/closure_linter/common/position.py -> build/bdist.macosx-10.6-universal/egg/closure_linter/common
copying build/lib/closure_linter/common/simplefileflags.py -> build/bdist.macosx-10.6-universal/egg/closure_linter/common
copying build/lib/closure_linter/common/tokenizer.py -> build/bdist.macosx-10.6-universal/egg/closure_linter/common
copying build/lib/closure_linter/common/tokens.py -> build/bdist.macosx-10.6-universal/egg/closure_linter/common
copying build/lib/closure_linter/ecmalintrules.py -> build/bdist.macosx-10.6-universal/egg/closure_linter
copying build/lib/closure_linter/ecmametadatapass.py -> build/bdist.macosx-10.6-universal/egg/closure_linter
copying build/lib/closure_linter/error_fixer.py -> build/bdist.macosx-10.6-universal/egg/closure_linter
copying build/lib/closure_linter/errorrules.py -> build/bdist.macosx-10.6-universal/egg/closure_linter
copying build/lib/closure_linter/errors.py -> build/bdist.macosx-10.6-universal/egg/closure_linter
copying build/lib/closure_linter/fixjsstyle.py -> build/bdist.macosx-10.6-universal/egg/closure_linter
copying build/lib/closure_linter/fixjsstyle_test.py -> build/bdist.macosx-10.6-universal/egg/closure_linter
copying build/lib/closure_linter/full_test.py -> build/bdist.macosx-10.6-universal/egg/closure_linter
copying build/lib/closure_linter/gjslint.py -> build/bdist.macosx-10.6-universal/egg/closure_linter
copying build/lib/closure_linter/indentation.py -> build/bdist.macosx-10.6-universal/egg/closure_linter
copying build/lib/closure_linter/javascriptlintrules.py -> build/bdist.macosx-10.6-universal/egg/closure_linter
copying build/lib/closure_linter/javascriptstatetracker.py -> build/bdist.macosx-10.6-universal/egg/closure_linter
copying build/lib/closure_linter/javascriptstatetracker_test.py -> build/bdist.macosx-10.6-universal/egg/closure_linter
copying build/lib/closure_linter/javascripttokenizer.py -> build/bdist.macosx-10.6-universal/egg/closure_linter
copying build/lib/closure_linter/javascripttokens.py -> build/bdist.macosx-10.6-universal/egg/closure_linter
copying build/lib/closure_linter/statetracker.py -> build/bdist.macosx-10.6-universal/egg/closure_linter
copying build/lib/closure_linter/tokenutil.py -> build/bdist.macosx-10.6-universal/egg/closure_linter
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/**init**.py to **init**.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/checker.py to checker.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/checkerbase.py to checkerbase.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/common/**init**.py to **init**.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/common/error.py to error.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/common/erroraccumulator.py to erroraccumulator.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/common/errorhandler.py to errorhandler.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/common/errorprinter.py to errorprinter.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/common/filetestcase.py to filetestcase.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/common/htmlutil.py to htmlutil.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/common/lintrunner.py to lintrunner.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/common/matcher.py to matcher.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/common/position.py to position.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/common/simplefileflags.py to simplefileflags.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/common/tokenizer.py to tokenizer.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/common/tokens.py to tokens.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/ecmalintrules.py to ecmalintrules.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/ecmametadatapass.py to ecmametadatapass.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/error_fixer.py to error_fixer.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/errorrules.py to errorrules.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/errors.py to errors.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/fixjsstyle.py to fixjsstyle.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/fixjsstyle_test.py to fixjsstyle_test.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/full_test.py to full_test.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/gjslint.py to gjslint.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/indentation.py to indentation.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/javascriptlintrules.py to javascriptlintrules.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/javascriptstatetracker.py to javascriptstatetracker.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/javascriptstatetracker_test.py to javascriptstatetracker_test.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/javascripttokenizer.py to javascripttokenizer.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/javascripttokens.py to javascripttokens.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/statetracker.py to statetracker.pyc
byte-compiling build/bdist.macosx-10.6-universal/egg/closure_linter/tokenutil.py to tokenutil.pyc
creating build/bdist.macosx-10.6-universal/egg/EGG-INFO
copying closure_linter.egg-info/PKG-INFO -> build/bdist.macosx-10.6-universal/egg/EGG-INFO
copying closure_linter.egg-info/SOURCES.txt -> build/bdist.macosx-10.6-universal/egg/EGG-INFO
copying closure_linter.egg-info/dependency_links.txt -> build/bdist.macosx-10.6-universal/egg/EGG-INFO
copying closure_linter.egg-info/entry_points.txt -> build/bdist.macosx-10.6-universal/egg/EGG-INFO
copying closure_linter.egg-info/requires.txt -> build/bdist.macosx-10.6-universal/egg/EGG-INFO
copying closure_linter.egg-info/top_level.txt -> build/bdist.macosx-10.6-universal/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/closure_linter-2.2.7-py2.6.egg' and adding 'build/bdist.macosx-10.6-universal/egg' to it
removing 'build/bdist.macosx-10.6-universal/egg' (and everything under it)
Processing closure_linter-2.2.7-py2.6.egg
Removing /Library/Python/2.6/site-packages/closure_linter-2.2.7-py2.6.egg
Copying closure_linter-2.2.7-py2.6.egg to /Library/Python/2.6/site-packages
closure-linter 2.2.7 is already the active version in easy-install.pth
Installing fixjsstyle script to /usr/local/bin
Installing gjslint script to /usr/local/bin

Installed /Library/Python/2.6/site-packages/closure_linter-2.2.7-py2.6.egg
Processing dependencies for closure-linter==2.2.7
Traceback (most recent call last):
  File "./setup.py", line 35, in <module>
    'fixjsstyle = closure_linter.fixjsstyle:main'
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/setuptools/command/install.py", line 76, in run
    self.do_egg_install()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/setuptools/command/install.py", line 104, in do_egg_install
    cmd.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/setuptools/command/easy_install.py", line 211, in run
    self.easy_install(spec, not self.no_deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/setuptools/command/easy_install.py", line 427, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/setuptools/command/easy_install.py", line 478, in install_item
    self.process_distribution(spec, dist, deps)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/setuptools/command/easy_install.py", line 519, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/pkg_resources.py", line 523, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/pkg_resources.py", line 2102, in requires
    dm = self._dep_map
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/pkg_resources.py", line 2094, in _dep_map
    for extra,reqs in split_sections(self._get_metadata(name)):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/pkg_resources.py", line 2513, in split_sections
    for line in yield_lines(s):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/pkg_resources.py", line 1807, in yield_lines
    for ss in strs:
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/pkg_resources.py", line 2116, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/pkg_resources.py", line 1134, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/pkg_resources.py", line 1131, in get_metadata
    return self._get(self._fn(self.egg_info,name))
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/pkg_resources.py", line 1191, in _get
    return self.loader.get_data(path)
zipimport.ZipImportError: bad local file header in /Library/Python/2.6/site-packages/closure_linter-2.2.7-py2.6.egg
make: **\* [install] Error 1
npm ERR! error installing linter@0.0.7 Error: linter@0.0.7 install: `make install`
npm ERR! error installing linter@0.0.7 `sh "-c" "make install"` failed with 2
npm ERR! error installing linter@0.0.7     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing linter@0.0.7     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing linter@0.0.7     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! linter@0.0.7 install: `make install`
npm ERR! `sh "-c" "make install"` failed with 2
npm ERR! 
npm ERR! Failed at the linter@0.0.7 install script.
npm ERR! This is most likely a problem with the linter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make install
npm ERR! You can get their info via:
npm ERR!     npm owner ls linter
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 10.7.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "linter"
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/camilo/Dropbox/Development/foo/bar/npm-debug.log
npm not ok

**Comment by c4milo** [comment]
btw, sudo easy_install http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz worked fine for me.

**Comment by fsateler** [comment]
There is no need to install closure linter globally. Just use it from the deps directory. At least it works for me. Doing npm install -f linter (so that npm doesn't remove the package after failing) works just fine
