### ISSUE TITLE
Installation fails on Mac

### ISSUE THREAD

**Issue by devdinu** [kof/node-linter#7]
Installation fails on Mac. following is the error.
I've used `npm install linter --no-optional`.
npm version 3.6.0
node version v5.7.0

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.7.0/bin/node" "/usr/local/bin/npm" "install" "linter" "--no-optional"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! linter@0.0.7 install: `make install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the linter@0.0.7 install script 'make install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the linter package,
npm ERR! not with npm itself.

# npm-debug.log
 verbose stack Error: linter@0.0.7 install: `make install`
2055 verbose stack Exit status 2
2055 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
2055 verbose stack     at emitTwo (events.js:100:13)
2055 verbose stack     at EventEmitter.emit (events.js:185:7)
2055 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
2055 verbose stack     at emitTwo (events.js:100:13)
2055 verbose stack     at ChildProcess.emit (events.js:185:7)
2055 verbose stack     at maybeClose (internal/child_process.js:827:16)
2055 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by luisnomad** [comment]
Same here, this is the reason:
```
cd ./deps/closure-linter && python ./setup.py install 
running install
Checking .pth file support in /Library/Python/2.7/site-packages/
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/test-easy-install-15757.pth'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /Library/Python/2.7/site-packages/
```

**Comment by leoguo-dev** [comment]
same with @luisnomad
